ACE-it/Controllers/ConfigurationIngredientsController.cs
using System.Linq;
using System.Threading.Tasks;
using ACE_it.Data;
using ACE_it.Helper;
using ACE_it.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ACE_it.Controllers
{
    public class ConfigurationIngredientsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ConfigurationIngredientsController(ApplicationDbContext context)
        {
            _context = context;
        }
       
        // GET: Ingredients
        public async Task<IActionResult> Index(
            string sortOrder, string currentFilter,
            string searchString, int? pageNumber)
        {
            var ingredients = from s in _context.Ingredients select s;
            
            var user = _context.AppUsers
                .First(r => r.Email == User.Identity.Name);

            var userIngredients = (from s in _context.UserFavouriteIngredients
                where s.UserId == user.Id select s)
                .Include(r => r.Ingredient)
                .ToListAsync();
            
            var userUnwanted = (from s in _context.UserUnwantedIngredients
                where s.UserId == user.Id select s)
                .ToListAsync();

            if (searchString != null)
                pageNumber = 1;
            else
                searchString = currentFilter;

            ingredients = Search(ingredients, searchString);
            ingredients = OrderSwitch(ingredients, sortOrder);

            var pageSize = 5;
            var i = await PaginatedList<Ingredient>.CreateAsync(
                ingredients.AsNoTracking(),
                pageNumber ?? 1, pageSize);
            
            
            return View(new ConfigurationIngredientViewModel(
                user, i, await userIngredients, await userUnwanted));
        }

        
        // PRIVATE
        
        private IQueryable<Ingredient> Search(
            IQueryable<Ingredient> ingredients, string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            if (!string.IsNullOrEmpty(searchString))
                ingredients = ingredients.Where(
                    s => s.Name.ToLower().Contains(
                        searchString.Trim().ToLower()));

            return ingredients;
        }

        private IQueryable<Ingredient> OrderSwitch(
            IQueryable<Ingredient> ingredients, string sortOrder)
        {
            ViewData["NameSortParam"] =
                string.IsNullOrEmpty(sortOrder) || sortOrder == "name_desc" ? "name_asc" : "name_desc";

            switch (sortOrder)
            {
                case "name_desc":
                    ingredients = ingredients.OrderByDescending(s => s.Name);
                    break;
                default:
                    ingredients = ingredients.OrderBy(s => s.Name);
                    break;
            }

            return ingredients;
        }
    }
}

ACE-it/Views/ConfigurationIngredients/Index.cshtml
@model ACE_it.Helper.ConfigurationIngredientViewModel;

@{
    ViewData["Title"] = "Ingredients";

    var prevDisabled = Model.Ingredients.HasPreviousPage ? "" : "disabled";
    var nextDisabled = Model.Ingredients.HasNextPage ? "" : "disabled";
}

<h1 class="mt-5" style="text-align: center">@Html.ViewData["Title"]</h1>

<div class="table-responsive my-5 table-centered">
    <table class="table table-striped">
        <thead>
        <tr>
            <th><a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParam"]"><p style="color:#28a745">Name</p></a></th>
            <th><div align="center"><p style="color:#28a745">Favourite Ingredient</p></div></th>
            <th><div align="center"><p style="color:#28a745">Unwanted Ingredient</p></div></th>
        </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Ingredients)
            {
                <tr>
                    <td>@item.Name</td>
                    <td><div align="center">
                        @if (Model.FavouriteIngredients.Find(r => r.IngredientId == item.Id) == null)
                        {                        
                            <form style="width: 25%" asp-action="Store" asp-controller="UserFavouriteIngredients" method="post">
                                <input style="display: none" name="pageNumber" value="@Model.Ingredients.PageIndex">
                                <input style="display: none" name="IngredientId" value="@item.Id"/>
                                <input style="display: none" name="UserId" value="@Model.User.Id"/>
                                <button type="submit" class="btn btn-outline-primary">Add</button>
                            </form>
                        }
                        else
                        {
                            <form style="width: 25%" asp-action="Delete" asp-controller="UserFavouriteIngredients" method="get">
                                <input style="display: none" name="pageNumber" value="@Model.Ingredients.PageIndex">
                                <input style="display: none" name="IngredientId" value="@item.Id"/>
                                <input style="display: none" name="UserId" value="@Model.User.Id"/>
                                <button type="submit" class="btn btn-outline-danger">Delete</button>
                            </form>
                        }
                    </div></td>
                    
                    <td><div align="center">
                        @if (Model.UnwantedIngredients.Find(r => r.IngredientId == item.Id) == null)
                        {                        
                            <form style="width: 25%" asp-action="Store" asp-controller="UserUnwantedIngredients" method="post">
                                <input style="display: none" name="pageNumber" value="@Model.Ingredients.PageIndex">
                                <input style="display: none" name="IngredientId" value="@item.Id"/>
                                <input style="display: none" name="UserId" value="@Model.User.Id"/>
                                <button type="submit" class="btn btn-outline-primary">Add</button>
                            </form>
                        }
                        else
                        {
                            <form style="width: 25%" asp-action="Delete" asp-controller="UserUnwantedIngredients" method="get">
                                <input style="display: none" name="pageNumber" value="@Model.Ingredients.PageIndex">
                                <input style="display: none" name="IngredientId" value="@item.Id"/>
                                <input style="display: none" name="UserId" value="@Model.User.Id"/>
                                <button type="submit" class="btn btn-outline-danger">Delete</button>
                            </form>
                        }
                    </div></td>
                </tr>
            }
        </tbody>
    </table>

    <div style="display: flex; justify-content: space-between;">
        <form style="width: 25%" asp-action="Index" method="get">
            <div class="form-group">
                <input type="text" class="form-control" name="SearchString" placeholder="Search by name" value="@ViewData["currentFilter"]">
            </div>
            <button type="submit" class="btn btn-primary" style="display: none"></button>
        </form>

        <nav aria-label="Navigation">
            <ul class="pagination justify-content-end">
                <li class="page-item @prevDisabled">
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="@(Model.Ingredients.PageIndex - 1)"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       class="page-link">
                        <<
                    </a>
                </li>

                @for (var i = 1; i <= Model.Ingredients.TotalPages; i++)
                {
                    <li class="page-item @(i == Model.Ingredients.PageIndex ? "active" : "")">
                        <a asp-action="Index" asp-route-sortOrder="@ViewData["CurrentSort"]"
                           asp-route-pageNumber="@i"
                           asp-route-currentFilter="@ViewData["CurrentFilter"]"
                           class="page-link">
                            @i
                        </a>
                    </li>
                }

                <li class="page-item @nextDisabled">
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="@(Model.Ingredients.PageIndex + 1)"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       class="page-link">
                        >>
                    </a>
                </li>
            </ul>
        </nav>
    </div>

</div>

ACE-it/Views/ConfigurationIngredients/Store.cshtml
@model ACE_it.Helper.PaginatedList<Ingredient>

@{
    ViewData["Title"] = "Ingredients";

    var prevDisabled = Model.HasPreviousPage ? "" : "disabled";
    var nextDisabled = Model.HasNextPage ? "" : "disabled";
}

<h1 class="mt-5" style="text-align: center">@Html.ViewData["Title"]</h1>

<div class="table-responsive my-5 table-centered">
    <table class="table">
        <thead class="thead-light">
        <tr>
            <th><a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParam"]"><p style="color:#28a745">Name</p></a></th>
            <th><div align="center"><p style="color:#28a745">Favourite Ingredient</p></div></th>
            <th><div align="center"><p style="color:#28a745">Unwanted Ingredient</p></div></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td><div align="center">
                    @if ((@item.UserFavouriteIngredients == null) || (@item.UserFavouriteIngredients != null && !@item.UserFavouriteIngredients.Contains(new UserFavouriteIngredient{UserId = "1", IngredientId = 1})))
                    {
                        <form style="width: 25%" asp-action="Store" asp-controller="ConfigurationIngredients" method="get">
                            <a type="submit">Add</a>
                        </form>
                    }
                    
                </div></td>
                <td><div align="center">
                    empty
                </div></td>
            </tr>
        }
    </table>

    <div style="display: flex; justify-content: space-between;">
        <form style="width: 25%" asp-action="Index" method="get">
            <div class="form-group">
                <input type="text" class="form-control" name="SearchString" placeholder="Search by name" value="@ViewData["currentFilter"]">
            </div>
            <button type="submit" class="btn btn-primary" style="display: none"></button>
        </form>

        <nav aria-label="Navigation">
            <ul class="pagination justify-content-end">
                <li class="page-item @prevDisabled">
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       class="page-link">
                        <<
                    </a>
                </li>

                @for (var i = 1; i <= Model.TotalPages; i++)
                {
                    <li class="page-item @(i == Model.PageIndex ? "active" : "")">
                        <a asp-action="Index" asp-route-sortOrder="@ViewData["CurrentSort"]"
                           asp-route-pageNumber="@i"
                           asp-route-currentFilter="@ViewData["CurrentFilter"]"
                           class="page-link">
                            @i
                        </a>
                    </li>
                }

                <li class="page-item @nextDisabled">
                    <a asp-action="Index" asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       class="page-link">
                        >>
                    </a>
                </li>
            </ul>
        </nav>
    </div>

</div>